name: Test Workflow

on: 
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: 23f2004770@ds.study.iitm.ac.in  # Step with your email
        run: echo "Hello, world!"
